name: probabilistic-programming
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pytorch-cpu
  - torchvision-cpu
  - ffmpeg
  - pip
  - pip:
      - pyro-ppl
